Repository depromeet/16th-team3-FE, pull requests merged in 2025-03, with the labels that each got.

#33 SCRUM-107 feat: 몰입 키워드 페이지 UI 구현
  public/icons/assignment.svg
  public/icons/calm.svg
  public/icons/clock-stopwatch.svg
  public/icons/design.svg
  public/icons/emotional.svg
  public/icons/excited.svg
  public/icons/exercise.svg
  public/icons/programming.svg
  public/icons/study.svg
  public/icons/urgent.svg
  public/icons/writing.svg
  src/app/create/_components/bufferTime/BufferTime.tsx
  src/app/create/_components/characterDialog/CharacterDialog.tsx
  src/app/create/_components/taskTypeChip/TaskTypeChip.tsx
  src/app/create/_components/taskTypeInput/TaskTypeInput.tsx
  src/app/create/page.tsx
  src/components/ui/dialog.tsx
  src/types/create.ts
Labels: enhancement

#20 SCRUM-118 사용자는 마감 시간을 지키기 위해 마감 시간을 선택하기를 원한다
  .github/workflows/build-check.yml
  public/icons/Error.svg
  src/app/create/_components/DateSelectedComponent/DateSelectedComponent.tsx
  src/app/create/_components/taskInput/TaskInput.tsx
  src/app/create/_components/timeSelectedComponent/TimeSelectedComponent.tsx
  src/app/create/page.tsx
  src/components/clearableInput/ClearableInput.tsx
  src/components/datePicker/DatePicker.tsx
  src/components/timePicker/Picker.tsx
  src/components/timePicker/TimePicker.tsx
  src/components/toast/Toast.tsx
  src/components/ui/calendar.tsx
  src/types/time.ts
Labels: enhancement

#24 SCRUM-41 사용자는-할-일을-시작하기-위해-작은-행동을-설정하기를-원한다
  public/icons/DrinkWater.svg
  public/icons/SitAtTheDesk.svg
  public/icons/TurnOnTheLaptop.svg
  src/app/create/_components/smallActionChip/SmallActionChip.tsx
  src/app/create/_components/smallActionInput/SmallActionInput.tsx
  src/app/create/_components/taskInput/TaskInput.tsx
  src/app/create/context.ts
  src/app/create/page.tsx
  src/components/clearableInput/ClearableInput.tsx
  src/types/create.ts
  src/types/time.ts
Labels: enhancement

#28 SCRUM-42 사용자는 충분한 시간 안에 할 일을 완수하기 위해 예상 소요시간을 설정하기를 원한다
  package-lock.json
  package.json
  public/icons/CheckedBox.svg
  public/icons/UnCheckedBox.svg
  src/app/create/_components/estimatedTimeInput/EstimatedTimeInput.tsx
  src/app/create/_components/headerTitle/HeaderTitle.tsx
  src/app/create/_components/smallActionInput/SmallActionInput.tsx
  src/app/create/_components/taskInput/TaskInput.tsx
  src/app/create/_components/timeSelectedComponent/TimeSelectedComponent.tsx
  src/app/create/page.tsx
  src/components/ui/tabs.tsx
Labels: enhancement

#34 SCRUM-43 사용자는 할 일을 시작하기 전에 버퍼타임이 적용된 것을 확인할 수 있기를 원한다
  src/app/create/_components/DateSelectedComponent/DateSelectedComponent.tsx
  src/app/create/_components/bufferTime/BufferTime.tsx
  src/app/create/_components/estimatedTimeInput/EstimatedTimeInput.tsx
  src/app/create/_components/smallActionInput/SmallActionInput.tsx
  src/app/create/_components/taskInput/TaskInput.tsx
  src/app/create/_components/timeSelectedComponent/TimeSelectedComponent.tsx
  src/app/create/context.ts
  src/app/create/page.tsx
  src/types/create.ts
Labels: enhancement

#37 SCRUM-26 사용자로서 할 일을 등록할 수 있는 서비스가 필요합니다
  .github/workflows/build-check.yml
  package-lock.json
  package.json
  public/icons/CheckedBox.svg
  public/icons/DrinkWater.svg
  public/icons/Error.svg
  public/icons/SitAtTheDesk.svg
  public/icons/TurnOnTheLaptop.svg
  public/icons/UnCheckedBox.svg
  public/icons/assignment.svg
  public/icons/calm.svg
  public/icons/clock-stopwatch.svg
  public/icons/design.svg
  public/icons/emotional.svg
  public/icons/excited.svg
  public/icons/exercise.svg
  public/icons/programming.svg
  public/icons/study.svg
  public/icons/urgent.svg
  public/icons/writing.svg
  src/app/create/_components/DateSelectedComponent/DateSelectedComponent.tsx
  src/app/create/_components/bufferTime/BufferTime.tsx
  src/app/create/_components/characterDialog/CharacterDialog.tsx
  src/app/create/_components/estimatedTimeInput/EstimatedTimeInput.tsx
  src/app/create/_components/headerTitle/HeaderTitle.tsx
  src/app/create/_components/smallActionChip/SmallActionChip.tsx
  src/app/create/_components/smallActionInput/SmallActionInput.tsx
  src/app/create/_components/taskInput/TaskInput.tsx
  src/app/create/_components/taskTypeChip/TaskTypeChip.tsx
  src/app/create/_components/taskTypeInput/TaskTypeInput.tsx
  src/app/create/_components/timeSelectedComponent/TimeSelectedComponent.tsx
  src/app/create/context.ts
  src/app/create/page.tsx
  src/app/layout.tsx
  src/app/providers.tsx
  src/components/clearableInput/ClearableInput.tsx
  src/components/datePicker/DatePicker.tsx
  src/components/timePicker/Picker.tsx
  src/components/timePicker/TimePicker.tsx
  src/components/toast/Toast.tsx
  src/components/ui/calendar.tsx
  src/components/ui/dialog.tsx
  src/components/ui/tabs.tsx
  src/types/create.ts
  src/utils/text.tsx
Labels: enhancement

#39 SCRUM-133 feat: 즉시 시작 퍼넬 구조 형성
  src/app/(create)/_components/DateSelectedComponent/DateSelectedComponent.tsx
  src/app/(create)/_components/bufferTime/BufferTime.tsx
  src/app/(create)/_components/characterDialog/CharacterDialog.tsx
  src/app/(create)/_components/estimatedTimeInput/EstimatedTimeInput.tsx
  src/app/(create)/_components/headerTitle/HeaderTitle.tsx
  src/app/(create)/_components/instantTaskTypeInput/InstantTaskTypeInput.tsx
  src/app/(create)/_components/smallActionChip/SmallActionChip.tsx
  src/app/(create)/_components/smallActionInput/SmallActionInput.tsx
  src/app/(create)/_components/taskInput/TaskInput.tsx
  src/app/(create)/_components/taskTypeChip/TaskTypeChip.tsx
  src/app/(create)/_components/taskTypeInput/TaskTypeInput.tsx
  src/app/(create)/_components/timeSelectedComponent/TimeSelectedComponent.tsx
  src/app/(create)/context.ts
  src/app/(create)/instant-create/page.tsx
  src/app/(create)/scheduled-create/page.tsx
  src/hooks/useMount.ts
  src/types/create.ts
  src/utils/getBufferTime.ts
  src/utils/text.tsx
  src/utils/transformTaskData.tsx
Labels: enhancement

#41 SCRUM-132 사용자는 즉시 할 일을 등록할 수 있기를 원한다
  public/icons/Bell.svg
  src/app/(create)/_components/bufferTime/BufferTime.tsx
  src/app/(create)/_components/characterDialog/CharacterDialog.tsx
  src/app/(create)/_components/dateSelectedComponent/DateSelectedComponent.tsx
  src/app/(create)/_components/estimatedTimeInput/EstimatedTimeInput.tsx
  src/app/(create)/_components/headerTitle/HeaderTitle.tsx
  src/app/(create)/_components/instantTaskTypeInput/InstantTaskTypeInput.tsx
  src/app/(create)/_components/smallActionChip/SmallActionChip.tsx
  src/app/(create)/_components/smallActionInput/SmallActionInput.tsx
  src/app/(create)/_components/taskInput/TaskInput.tsx
  src/app/(create)/_components/taskTypeChip/TaskTypeChip.tsx
  src/app/(create)/_components/taskTypeInput/TaskTypeInput.tsx
  src/app/(create)/_components/timeSelectedComponent/TimeSelectedComponent.tsx
  src/app/(create)/context.ts
  src/app/(create)/instant-create/page.tsx
  src/app/(create)/scheduled-create/page.tsx
  src/hooks/useMount.ts
  src/types/create.ts
  src/utils/getBufferTime.ts
  src/utils/text.tsx
  src/utils/transformTaskData.tsx
Labels: enhancement

#43 SCRUM-136 time picker 라이브러리 대체
  .vscode/settings.json
  package-lock.json
  package.json
  src/app/(create)/_components/estimatedTimeInput/EstimatedTimeInput.tsx
  src/app/(create)/_components/instantTaskTypeInput/InstantTaskTypeInput.tsx
  src/app/(create)/_components/taskTypeInput/TaskTypeInput.tsx
  src/components/timePicker/TimePicker.tsx
  src/components/timePicker/Wheel.tsx
  src/components/timePicker/style.css
  src/utils/transformTaskData.tsx
Labels: enhancement

#45 SCRUM-137 fix: 할 일 등록 일부 버그 수정
  src/app/(create)/_components/bufferTime/BufferTime.tsx
  src/app/(create)/_components/estimatedTimeInput/EstimatedTimeInput.tsx
  src/app/(create)/_components/taskInput/TaskInput.tsx
  src/app/(create)/_components/taskTypeInput/TaskTypeInput.tsx
  src/app/(create)/_components/timeSelectedComponent/TimeSelectedComponent.tsx
  src/app/(create)/scheduled-create/page.tsx
  src/components/timePicker/TimePicker.tsx
  src/utils/formatBufferTime.ts
  src/utils/getBufferTime.ts
Labels: bug

#46 SCRUM-67 feat: 카카오 로그인 적용
  .vscode/settings.json
  package.json
  src/app/(create)/_components/estimatedTimeInput/EstimatedTimeInput.tsx
  src/app/(create)/_components/timeSelectedComponent/TimeSelectedComponent.tsx
  src/app/(root)/page.tsx
  src/app/api/oauth/callback/kakao/route.ts
  src/app/api/oauth/test/route.ts
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/oauth/callback/kakao/page.tsx
  src/app/page.tsx
  src/middleware.ts
Labels: enhancement

#52 Scrum 25 사용자로서 할 일 목록을 확인할 수 있는 서비스가 필요합니다
  src/app/api/tasks/current-week/route.ts
  src/app/home-page/_components/AllTaskItem.tsx
  src/app/home-page/_components/InProgressTaskItem.tsx
  src/app/home-page/page.tsx
  src/services/taskService.ts
  src/types/task.ts
Labels: enhancement

#54 feat: 로그인 화면 구현
  public/icons/login/apple.svg
  public/icons/login/kakao.svg
  src/app/login-page/page.tsx
Labels: enhancement

#56 Scrum 145 사용자로서 온보딩을 볼 수 있는 화면이 필요합니다
  public/icons/onboarding/onboarding1.svg
  public/icons/onboarding/onboarding2.svg
  public/icons/onboarding/onboarding3.svg
  public/icons/onboarding/onboarding4.svg
  src/app/onboarding/page.tsx
Labels: help wanted

#51 SCRUM-140 feat: 토큰 관리
  package-lock.json
  package.json
  src/app/(create)/_components/instantTaskTypeInput/InstantTaskTypeInput.tsx
  src/app/(create)/context.ts
  src/app/(create)/instant-create/page.tsx
  src/app/api/oauth/callback/kakao/route.ts
  src/app/api/oauth/test/route.ts
  src/app/login-test/page.tsx
  src/app/oauth/callback/kakao/page.tsx
  src/app/page.tsx
  src/lib/ky.ts
  src/middleware.ts
  src/store/useUserStore.ts
  src/types/user.ts
Labels: enhancement

#57 SCRUM-147 feat: 작업 생성 후 홈 페이지로 이동 및 모달 띄우기
  src/app/(create)/_components/characterDialog/CharacterDialog.tsx
  src/app/(create)/_components/instantTaskTypeInput/InstantTaskTypeInput.tsx
  src/app/(create)/_components/taskTypeInput/TaskTypeInput.tsx
  src/app/(create)/instant-create/page.tsx
  src/app/(create)/scheduled-create/page.tsx
  src/app/home-page/page.tsx
  src/middleware.ts
Labels: enhancement

#58 SCRUM-147 feat: 작업 생성 후 홈 페이지로 이동 및 모달 띄우기 (#57)
  src/app/(create)/_components/characterDialog/CharacterDialog.tsx
  src/app/(create)/_components/instantTaskTypeInput/InstantTaskTypeInput.tsx
  src/app/(create)/_components/taskTypeInput/TaskTypeInput.tsx
  src/app/(create)/instant-create/page.tsx
  src/app/(create)/scheduled-create/page.tsx
  src/app/home-page/page.tsx
  src/middleware.ts
Labels: enhancement

#59 SCRUM-141 애플 로그인 구현
  .github/workflows/build-check.yml
  .github/workflows/github-actions.yml
  .vscode/settings.json
  src/app/(create)/scheduled-create/page.tsx
  src/app/api/oauth/callback/apple/route.ts
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/oauth/callback/apple/page.tsx
  src/app/oauth/callback/kakao/page.tsx
  src/app/page.tsx
  src/middleware.ts
  src/types/auth.ts
Labels: enhancement

#61 SCRUM-146 로그인 화면 적용
  src/app/(create)/_components/characterDialog/CharacterDialog.tsx
  src/app/home-page/page.tsx
  src/app/home-page/weekly-tasks/page.tsx
  src/app/login-page/page.tsx
  src/app/login/page.tsx
  src/app/oauth/callback/kakao/page.tsx
  src/components/loader/Loader.tsx
  src/lib/ky.ts
Labels: enhancement

#73 feat: 서버사이드용 ky 추가
  src/app/api/tasks/home/route.ts
  src/lib/serverKy.ts
Labels: enhancement

#80 SCRUM-154 feat: 작업 수정 시간 예외처리
  .vscode/settings.json
  src/app/(create)/_components/bufferTime/BufferTime.tsx
  src/app/(create)/_components/taskTypeInput/TaskTypeInput.tsx
  src/app/api/tasks/[taskId]/route.ts
  src/app/api/tasks/home/route.ts
  src/app/authProvider.tsx
  src/app/edit/buffer-time/[taskId]/page.tsx
  src/app/edit/context.ts
  src/app/edit/deadline-date/[taskId]/page.tsx
  src/app/edit/estimated-time/[taskId]/page.tsx
  src/app/edit/small-action/[taskId]/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/components/timePicker/style.css
  src/components/ui/drawer.tsx
  src/lib/ky.ts
  src/lib/serverKy.ts
  src/services/taskService.ts
  src/static/fonts/PretendardVariable.woff2
  src/utils/dateFormat.ts
  src/utils/getBufferTime.ts
  tailwind.config.ts
Labels: bug, enhancement

#84 fix: 마이페이지 프로필 이미지 로딩 에러 수정
  next.config.ts
  src/app/(create)/_components/bufferTime/BufferTime.tsx
  src/app/(create)/_components/taskTypeInput/TaskTypeInput.tsx
  src/app/my-page/page.tsx
  src/components/ProfileImage.tsx
Labels: bug

#88 refactor: 로그아웃 / 회원탈퇴 api routes 적용
  package-lock.json
  src/app/(create)/_components/bufferTime/BufferTime.tsx
  src/app/(create)/_components/characterDialog/CharacterDialog.tsx
  src/app/(root)/_components/CreateTaskSheet.tsx
  src/app/(root)/page.tsx
  src/app/api/auth/logout/route.ts
  src/app/api/auth/members/me/route.ts
  src/app/api/auth/withdraw/route.ts
  src/app/authProvider.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/my-page/page.tsx
  src/components/ui/drawer.tsx
  src/lib/serverKy.ts
  src/middleware.ts
Labels: enhancement

#89 fix: 하단 버튼 위치 수정 / 작업 생성 시, 로딩 ux 개선
  src/app/(create)/_components/bufferTime/BufferTime.tsx
  src/app/(create)/_components/estimatedTimeInput/EstimatedTimeInput.tsx
  src/app/(create)/_components/instantTaskTypeInput/InstantTaskTypeInput.tsx
  src/app/(create)/_components/smallActionInput/SmallActionInput.tsx
  src/app/(create)/_components/taskInput/TaskInput.tsx
  src/app/(create)/_components/taskTypeInput/TaskTypeInput.tsx
  src/app/(create)/instant-create/page.tsx
  src/app/(create)/scheduled-create/page.tsx
  src/app/login/page.tsx
  src/components/loader/Loader.tsx
  src/middleware.ts
Labels: enhancement

#90 fix: 유저 정보가 없는 경우 불러올 수 있도록 수정
  src/app/api/auth/members/me/route.ts
  src/app/login/page.tsx
  src/app/my-page/page.tsx
  src/middleware.ts
Labels: bug

#94 feat: 문의사항 추가 및 구글폼 연결
  src/app/(protected)/my-page/page.tsx
  src/app/(protected)/open-source/page.tsx
  src/app/api/tasks/home/route.ts
  src/lib/serverKy.ts
  src/middleware.ts
Labels: enhancement

#98 remove: 로그인 device 관련 데이터 제거
  src/app/(auth)/login/page.tsx
  src/app/(protected)/(create)/_components/characterDialog/CharacterDialog.tsx
  src/app/(protected)/(root)/page.tsx
  src/app/api/oauth/callback/apple/route.ts
  src/app/api/oauth/callback/kakao/route.ts
  src/app/layout.tsx
Labels: bug

#102 refactor: 할 일 등록 qa 2차 수정
  src/app/(protected)/(create)/_components/dateSelectedComponent/DateSelectedComponent.tsx
  src/app/(protected)/(create)/_components/taskInput/TaskInput.tsx
  src/app/(protected)/(create)/_components/timeSelectedComponent/TimeSelectedComponent.tsx
  src/components/clearableInput/ClearableInput.tsx
  src/components/datePicker/DatePicker.tsx
  src/components/timePicker/Wheel.tsx
  src/components/timePicker/style.css
  src/components/toast/Toast.tsx
  src/components/ui/calendar.tsx
  src/hooks/useInitialTime.ts
  tailwind.config.ts
Labels: refactor

#107 refactor: 작은 행동 입력 스타일링 및 일부 기능 개선
  src/app/(auth)/login/page.tsx
  src/app/(protected)/(create)/_components/bufferTime/BufferTime.tsx
  src/app/(protected)/(create)/_components/characterDialog/CharacterDialog.tsx
  src/app/(protected)/(create)/_components/dateSelectedComponent/DateSelectedComponent.tsx
  src/app/(protected)/(create)/_components/estimatedTimeInput/EstimatedTimeInput.tsx
  src/app/(protected)/(create)/_components/instantTaskTypeInput/InstantTaskTypeInput.tsx
  src/app/(protected)/(create)/_components/smallActionInput/SmallActionInput.tsx
  src/app/(protected)/(create)/_components/taskInput/TaskInput.tsx
  src/app/(protected)/(create)/instant-create/page.tsx
  src/app/(protected)/(create)/scheduled-create/page.tsx
  src/app/(protected)/(root)/page.tsx
  src/app/(protected)/signup-complete/page.tsx
  src/app/api/tasks/scheduled/route.ts
  src/app/api/tasks/urgent/route.ts
Labels: bug, enhancement

#108 refactor: 할 일 수정 스타일링 및 일부 기능 개선
  src/app/(protected)/(create)/_components/characterDialog/CharacterDialog.tsx
  src/app/(protected)/(create)/_components/estimatedTimeInput/EstimatedTimeInput.tsx
  src/app/(protected)/(root)/_components/TaskDetailSheet.tsx
  src/app/(protected)/(root)/page.tsx
  src/app/(protected)/edit/buffer-time/[taskId]/page.tsx
  src/app/(protected)/edit/deadline-date/[taskId]/page.tsx
  src/app/(protected)/edit/estimated-time/[taskId]/page.tsx
  src/app/(protected)/edit/layout.tsx
  src/app/(protected)/edit/small-action/[taskId]/page.tsx
Labels: bug, enhancement

#110 fix: 할 일 수정 시, 즉시 시작 바텀시트 하드코딩 값 수정 / 바텀시트 Drawer 적용
  src/app/(protected)/(root)/_components/InProgressTaskItem.tsx
  src/app/(protected)/edit/deadline-date/[taskId]/page.tsx
Labels: bug
